
server:
  port: 8888
  servlet:
    context-path: /

spring:
  application:
    name: store
  datasource:
    name:
    url: jdbc:mysql://127.0.0.1:3306/wms_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
